services:

  backend:
    build: ./Back/
    container_name: ${APP_NAME}_backend
    environment:
      - MARIADB_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${SQL_DATABASE}
      - MARIADB_USER=${SQL_USER}
      - MARIADB_PASSWORD=${SQL_PASSWORD}
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}

    volumes:
      - ./Back/TFG:/usr/src/app/

    ports:
      - ${HTTP_PORT}:8000

    networks:
      - tfg

    restart: always

  frontend:
    build: ./Front/
    container_name: ${APP_NAME}_frontend
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR_PORT=2467
    volumes:
      - ./Front/TFG:/app
      - node_modules:/app/node_modules
    ports:
      - ${REACT_PORT}:5173
      - 24678:24678
    networks:
      - tfg
    depends_on:
      - backend
    restart: always

networks:
  tfg:
    name: ${APP_NAME}_network

volumes:
 node_modules: