services:

  db:
    image: mariadb:11
    container_name: ${APP_NAME}_db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
    ports:
      - "${SQL_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - tfg
    healthcheck:
      test: ["CMD-SHELL", "mariadb -hlocalhost -u$SQL_USER -p$SQL_PASSWORD -e 'SELECT 1;' $SQL_DATABASE"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build: ./Back/
    container_name: ${APP_NAME}_backend
    environment:
      - MARIADB_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${SQL_DATABASE}
      - MARIADB_USER=${SQL_USER}
      - MARIADB_PASSWORD=${SQL_PASSWORD}
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - MYPROJECT_STAGE=${MYPROJECT_STAGE}
    volumes:
      - ./Back/TFG:/usr/src/app/
    ports:
      - ${HTTP_PORT}:8000
    networks:
      - tfg
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build: ./Front/
    container_name: ${APP_NAME}_frontend
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR_PORT=2467
    volumes:
      - ./Front/TFG:/app
      - node_modules:/app/node_modules
    ports:
      - ${REACT_PORT}:5173
      - 24678:24678
    networks:
      - tfg
    depends_on:
      - backend
    restart: always

networks:
  tfg:
    name: ${APP_NAME}_network

volumes:
  node_modules:
  mariadb_data:
