# Generated by Django 5.1.2 on 2025-06-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestamarket', '0002_answeroption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyinstance',
            name='state',
        ),
    ]
