# Generated by Django 5.1.2 on 2025-06-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestamarket', '0003_remove_surveyinstance_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
