# Generated by Django 5.1.2 on 2025-05-19 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_pendiente', '0002_role_remove_user_rol_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nombre_pendiente.role'),
        ),
    ]
